# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4222c1958fab6e4c3a091844ab4b83783f18fb444ea30abcb3248b273257dd63369b8268b8152a4dc841be5d405d506812dfc27be4e587857ab98017f54631f4

test:
  secret_key_base: ce5f5a38ce31d7a9a634899f5eaa0a8083a4887eebf195912445d3895f0f39deb00d4b65eed2051024aacebd8bbf8d8691de4a4f7ae8c2dc7e446e565c349636

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
